# Generated by Django 2.0.6 on 2020-06-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=200, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
