# Generated by Django 2.0.6 on 2020-06-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=30, null=True)),
                ('eventcategory', models.CharField(max_length=30, null=True)),
                ('eventdescription', models.TextField(null=True)),
                ('eventdate', models.CharField(max_length=30, null=True)),
                ('eventtime', models.CharField(max_length=30, null=True)),
                ('eventlocation', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
